import { db } from "./firebase-config.js";
import { collection, addDoc, getDocs } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";
const examSelect=document.getElementById("examSelect"),classSelect=document.getElementById("examClass"),sectionSelect=document.getElementById("questionSection");
function escapeHTML(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]));}function value(id){return document.getElementById(id)?.value.trim()||"";}
async function loadQuestionSettings(){try{const s=await getDocs(collection(db,"settings"));let settings=null;s.forEach(d=>{if(d.id==="config")settings=d.data();});if(!settings)s.forEach(d=>{const x=d.data();if(Array.isArray(x.classes)||Array.isArray(x.sections))settings=x;});const classes=Array.isArray(settings?.classes)?settings.classes:[],sections=Array.isArray(settings?.sections)?settings.sections:[];classSelect.innerHTML='<option value="">Select Class</option>'+classes.map(c=>`<option value="${escapeHTML(c)}">Class ${escapeHTML(c)}</option>`).join("");sectionSelect.innerHTML='<option value="">Select Section</option>'+sections.map(s=>`<option value="${escapeHTML(s)}">${escapeHTML(s)}</option>`).join("");localStorage.setItem("questionSettings",JSON.stringify({classes,sections}));}catch(e){console.error(e);alert("Unable to load Class/Section settings. Please check Admin Settings.");}}
async function loadExams(){try{const s=await getDocs(collection(db,"exams"));examSelect.innerHTML='<option value="">Select Assessment</option>';s.forEach(d=>{const e=d.data();examSelect.innerHTML+=`<option value="${escapeHTML(d.id)}">${escapeHTML(e.examName||"Unnamed Assessment")}</option>`});}catch(e){console.error(e);examSelect.innerHTML='<option value="">Unable to load assessments</option>';}}
function selectedTrueFalse(){return document.querySelector('input[name="trueFalseAnswer"]:checked')?.value||"";}
window.saveQuestion=async function(){try{const examId=value("examSelect"),examClass=value("examClass"),section=value("questionSection"),questionType=value("questionType"),question=questionType==="fillblank"?value("fillQuestion"):value("question"),marksValue=value("marks");if(!examId||!examClass||!section||!question||!marksValue){alert("Please select Class, Section and Assessment, then enter the Question and Marks.");return;}const marks=Number(marksValue);if(!Number.isFinite(marks)||marks<=0){alert("Please enter valid marks greater than 0.");return;}const data={examId,class:examClass,section,questionType,question,marks};
if(questionType==="mcq"){data.optionA=value("optionA");data.optionB=value("optionB");data.optionC=value("optionC");data.optionD=value("optionD");data.answer=value("answer");if(!data.optionA||!data.optionB||!data.optionC||!data.optionD||!data.answer){alert("Single Correct Answer MCQ: enter all four options and select ONE correct answer.");return;}}
else if(questionType==="multiple"){data.optionA=value("optionA");data.optionB=value("optionB");data.optionC=value("optionC");data.optionD=value("optionD");data.answers=["A","B","C","D"].filter(k=>document.getElementById("ans"+k)?.checked);if(!data.optionA||!data.optionB||!data.optionC||!data.optionD){alert("Multiple Correct Answers MCQ: enter all four options.");return;}if(data.answers.length<2){alert("Multiple Correct Answers MCQ requires at least TWO correct options. Select two or more checkboxes.");return;}}
else if(questionType==="truefalse"){data.optionA="True";data.optionB="False";data.answer=selectedTrueFalse();if(!data.answer){alert("Select either True or False as the correct answer.");return;}}
else if(questionType==="fillblank"){data.blankAnswers=value("blankAnswer").split("|").map(x=>x.trim()).filter(Boolean);data.answer=data.blankAnswers[0]||"";if(!data.blankAnswers.length){alert("Enter the expected answer for the blank.");return;}}
else if(questionType==="sentence"){data.modelAnswer=value("modelAnswer");}
await addDoc(collection(db,"questions"),data);alert("Question Saved Successfully");clearForm();}catch(e){console.error("Question Save Error:",e);alert("Unable To Save Question\n\n"+e.message);}};
function clearForm(){["questionId","question","fillQuestion","optionA","optionB","optionC","optionD","answer","blankAnswer","marks","modelAnswer"].forEach(id=>{const el=document.getElementById(id);if(el)el.value=""});["ansA","ansB","ansC","ansD"].forEach(id=>{const el=document.getElementById(id);if(el)el.checked=false});document.querySelectorAll('input[name="trueFalseAnswer"]').forEach(x=>x.checked=false);document.getElementById("questionType").value="mcq";if(typeof updateQuestionType==="function")updateQuestionType();}
loadQuestionSettings();loadExams();