import { db } from "./firebase-config.js";
import { collection,getDocs,addDoc,doc,getDoc,query,where } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";

let questions=[];let currentQuestion=0;let answers={};let exam={};let examId=localStorage.getItem("currentExamId");let timerInterval=null;let remainingSeconds=0;let submitting=false;

if(!examId){alert("Assessment not selected.");window.location.href="dashboard.html";}
window.previousQuestion=previousQuestion;window.nextQuestion=nextQuestion;

function typeOf(q){const t=String(q.questionType||q.type||"mcq").toLowerCase().trim();if(["multiple","multiple answer","multiple-answer","multiple answers"].includes(t))return"multiple";if(["truefalse","true/false","true false","tf"].includes(t))return"truefalse";if(["fillblank","fill in the blanks","fill-in-the-blanks","blank"].includes(t))return"fillblank";if(["sentence","subjective","descriptive","descriptive answer"].includes(t))return"sentence";return"mcq";}
function normalizeText(v){return String(v??"").trim().replace(/\s+/g," ").toLowerCase();}
function shuffleSeeded(arr,seed){let a=[...arr];let x=seed>>>0;for(let i=a.length-1;i>0;i--){x=(x*1664525+1013904223)>>>0;const j=x%(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;}
function makeSeed(){const identity=[localStorage.getItem("studentName")||"",localStorage.getItem("rollNo")||"",localStorage.getItem("studentClass")||"",localStorage.getItem("studentSection")||"",examId].join("|");let h=2166136261;for(let i=0;i<identity.length;i++){h^=identity.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}

async function loadExam(){try{const snap=await getDoc(doc(db,"exams",examId));if(!snap.exists()){alert("Assessment not found.");window.location.href="dashboard.html";return false;}exam=snap.data();const title=document.getElementById("examTitle"),loading=document.getElementById("loadingTitle");if(title)title.innerText=exam.examName||"Online Examination";if(loading)loading.innerText=exam.examName||"Online Examination";const duration=Number(exam.duration||0);if(duration>0){remainingSeconds=duration*60;startTimer();}else updateTimerDisplay();return true;}catch(e){console.error(e);alert("Unable to load assessment.");return false;}}

async function loadQuestions(){try{const snap=await getDocs(query(collection(db,"questions"),where("examId","==",examId)));let loaded=[];snap.forEach(d=>loaded.push({id:d.id,...d.data()}));if(!loaded.length){questions=[];const el=document.getElementById("questionText");if(el)el.innerText="No Questions Found";return;}
 const savedKey="examQuestionOrder_"+examId+"_"+(localStorage.getItem("rollNo")||localStorage.getItem("studentName")||"student");let orderedIds=[];try{orderedIds=JSON.parse(localStorage.getItem(savedKey)||"[]");}catch(e){}
 const byId=new Map(loaded.map(q=>[q.id,q]));let ordered=orderedIds.map(id=>byId.get(id)).filter(Boolean);const remaining=loaded.filter(q=>!orderedIds.includes(q.id));
 if(!ordered.length||ordered.length!==loaded.length){ordered=shuffleSeeded(loaded,makeSeed());localStorage.setItem(savedKey,JSON.stringify(ordered.map(q=>q.id)));}
 questions=ordered;currentQuestion=0;showQuestion();console.log("Questions shuffled for student:",questions.map(q=>q.id));
 }catch(e){console.error("Question Loading Error:",e);const el=document.getElementById("questionText");if(el)el.innerText="Unable to load questions.";}}

function showQuestion(){if(!questions.length)return;const q=questions[currentQuestion],type=typeOf(q),qid=q.id;const questionText=document.getElementById("questionText"),optionsDiv=document.getElementById("options");if(questionText)questionText.innerText=(currentQuestion+1)+". "+(q.question||"");if(!optionsDiv)return;optionsDiv.innerHTML="";
 if(type==="sentence"){const label=document.createElement("div");label.innerText="Your Answer:";label.style.fontWeight="bold";label.style.marginBottom="10px";optionsDiv.appendChild(label);const ta=document.createElement("textarea");ta.id="descriptiveAnswer";ta.placeholder="Write your answer here...";ta.rows=8;ta.style.cssText="width:100%;padding:12px;box-sizing:border-box;border-radius:8px;border:1px solid #ccc;resize:vertical";ta.value=answers[qid]||"";ta.addEventListener("input",()=>answers[qid]=ta.value);optionsDiv.appendChild(ta);updateNavigation();return;}
 if(type==="fillblank"){const label=document.createElement("div");label.innerText="Your Answer:";label.style.fontWeight="bold";label.style.marginBottom="10px";optionsDiv.appendChild(label);const input=document.createElement("input");input.type="text";input.id="fillBlankAnswer";input.placeholder="Type the missing answer";input.style.cssText="width:100%;padding:13px;box-sizing:border-box;border-radius:8px;border:1px solid #ccc;font-size:16px";input.value=answers[qid]||"";input.addEventListener("input",()=>answers[qid]=input.value);optionsDiv.appendChild(input);updateNavigation();return;}
 if(type==="truefalse"){["True","False"].forEach(v=>{const b=document.createElement("button");b.type="button";b.className="option-btn";b.innerText=v;b.style.display="block";b.style.width="100%";b.style.marginBottom="10px";if(answers[qid]===v)b.classList.add("selected");b.onclick=()=>saveAnswer(v);optionsDiv.appendChild(b);});updateNavigation();return;}
 if(type==="multiple"){const selected=Array.isArray(answers[qid])?answers[qid]:[];const heading=document.createElement("div");heading.innerText="Select all correct answers:";heading.style.fontWeight="bold";heading.style.marginBottom="10px";optionsDiv.appendChild(heading);["A","B","C","D"].forEach(k=>{const text=q["option"+k]||"";if(!text)return;const label=document.createElement("label");label.style.display="flex";label.style.alignItems="center";label.style.gap="10px";label.style.padding="12px";label.style.marginBottom="8px";label.style.border="1px solid #ddd";label.style.borderRadius="8px";label.style.cursor="pointer";const cb=document.createElement("input");cb.type="checkbox";cb.checked=selected.includes(k);cb.style.width="20px";cb.style.height="20px";cb.onchange=()=>{let next=Array.isArray(answers[qid])?[...answers[qid]]:[];if(cb.checked&&!next.includes(k))next.push(k);if(!cb.checked)next=next.filter(x=>x!==k);answers[qid]=next;};label.appendChild(cb);const span=document.createElement("span");span.innerText=k+". "+text;label.appendChild(span);optionsDiv.appendChild(label);});updateNavigation();return;}
 ["A","B","C","D"].forEach(k=>{const text=q["option"+k]||"";if(!text)return;const b=document.createElement("button");b.type="button";b.className="option-btn";b.innerText=k+". "+text;if(answers[qid]===k)b.classList.add("selected");b.onclick=()=>saveAnswer(k);optionsDiv.appendChild(b);});updateNavigation();}

function saveAnswer(answer){answers[questions[currentQuestion].id]=answer;showQuestion();}
function previousQuestion(){if(currentQuestion>0){currentQuestion--;showQuestion();}}
function nextQuestion(){if(currentQuestion<questions.length-1){currentQuestion++;showQuestion();}}
function updateNavigation(){const p=document.querySelector(".previous-btn"),n=document.querySelector(".next-btn");if(p)p.disabled=currentQuestion===0;if(n)n.disabled=currentQuestion===questions.length-1;}

function startTimer(){clearInterval(timerInterval);updateTimerDisplay();timerInterval=setInterval(()=>{remainingSeconds--;updateTimerDisplay();if(remainingSeconds<=0){clearInterval(timerInterval);alert("Time is over. Your assessment will be submitted automatically.");submitExam(true);}},1000);}
function updateTimerDisplay(){const timer=document.getElementById("timer");if(!timer)return;timer.innerText=String(Math.floor(remainingSeconds/60)).padStart(2,"0")+":"+String(remainingSeconds%60).padStart(2,"0");if(remainingSeconds<=60)timer.style.color="red";}

function compareFillBlank(student,correct){const s=String(student??"").trim();const c=String(correct??"").trim();if(c.includes("|")){const sa=s.split("|").map(normalizeText),ca=c.split("|").map(normalizeText);return sa.length===ca.length&&sa.every((v,i)=>v===ca[i]);}return normalizeText(s)===normalizeText(c);}
function compareMultiple(student,correct){const a=Array.isArray(student)?student:[];const b=Array.isArray(correct)?correct:[];return a.length===b.length&&[...a].sort().join(",")===[...b].sort().join(",");}

async function submitExam(autoSubmit=false){if(submitting)return;if(!questions.length){alert("No questions available.");return;}if(!autoSubmit&&!confirm("Are you sure you want to submit the assessment?"))return;submitting=true;if(timerInterval)clearInterval(timerInterval);let automaticMarks=0,totalMarks=0,correctAnswers=0,hasDescriptiveQuestions=false,subjectiveAnswers=[],review=[];
 questions.forEach(q=>{const marks=Number(q.marks||1);totalMarks+=marks;const type=typeOf(q),studentAnswer=answers[q.id]??"";let isCorrect=false;
 if(type==="sentence"){hasDescriptiveQuestions=true;subjectiveAnswers.push({questionId:q.id||"",question:q.question||"",studentAnswer,maxMarks:marks,teacherMarks:null,teacherRemark:"",evaluationStatus:"pending"});review.push({questionId:q.id||"",question:q.question||"",questionType:"sentence",selectedAnswer:studentAnswer,correctAnswer:"",marks:0,totalMarks:marks,isCorrect:null,evaluationStatus:"pending"});return;}
 if(type==="multiple")isCorrect=compareMultiple(studentAnswer,q.answers);else if(type==="fillblank")isCorrect=compareFillBlank(studentAnswer,q.answer);else isCorrect=normalizeText(studentAnswer)===normalizeText(q.answer||"");if(isCorrect){automaticMarks+=marks;correctAnswers++;}review.push({questionId:q.id||"",question:q.question||"",questionType:type,optionA:q.optionA||"",optionB:q.optionB||"",optionC:q.optionC||"",optionD:q.optionD||"",selectedAnswer:studentAnswer,correctAnswer:q.answer||q.answers||"",explanation:q.explanation||"Not Available",marks:isCorrect?marks:0,totalMarks:marks,isCorrect,evaluationStatus:"automatic"});});
 let score=automaticMarks,percentage=0,reviewStatus="not_required",resultPublished=true;if(hasDescriptiveQuestions){reviewStatus="pending";resultPublished=false;}else percentage=totalMarks>0?(score/totalMarks)*100:0;
 const studentName=localStorage.getItem("studentName")||"",studentClass=localStorage.getItem("studentClass")||"",studentSection=localStorage.getItem("studentSection")||"",rollNo=localStorage.getItem("rollNo")||"";
 try{const resultRef=await addDoc(collection(db,"results"),{studentName,studentClass,studentSection,rollNo,examId,examName:exam.examName||"",subject:exam.subject||"",examClass:exam.examClass||"",score,automaticMarks,descriptiveMarks:0,totalMarks,correctAnswers,totalQuestions:questions.length,percentage:Number(percentage.toFixed(2)),review,subjectiveAnswers,hasDescriptiveQuestions,reviewStatus,resultPublished,reviewedBy:"",reviewedAt:null,submittedAt:new Date().toISOString(),questionOrder:questions.map(q=>q.id)});localStorage.setItem("latestResultId",resultRef.id);localStorage.setItem("latestScore",score);localStorage.setItem("latestTotal",totalMarks);localStorage.setItem("latestPercentage",percentage.toFixed(2));localStorage.setItem("latestCorrectAnswers",correctAnswers);
 if(hasDescriptiveQuestions)alert("Assessment Submitted Successfully!\n\nYour descriptive answers are pending teacher evaluation.\n\nYour final marks and result will be published after teacher evaluation.");else alert("Exam Submitted Successfully!\n\nScore: "+score+"/"+totalMarks+"\nPercentage: "+percentage.toFixed(2)+"%");window.location.href=hasDescriptiveQuestions?"dashboard.html":"result.html?id="+resultRef.id;
 }catch(e){submitting=false;console.error("RESULT SAVE ERROR:",e);alert("Failed to save result.\n\n"+e.message);}}

async function initializeExam(){const ok=await loadExam();if(ok)await loadQuestions();}
window.submitExam=submitExam;initializeExam();
